### PR TITLE
Goom++ - Initial commit (complete rewrite in C++17).

### PR DESCRIPTION
**Pull request by glk1001**
Complete rewrite of 'C' Goom in C++17 - so new name is Goom++.

Same algorithms (different tentacles) and lots more color from Gurki's 'vivid' library. Now use clang-tidy and clang-format for code checking.

Have tested on Ubuntu 22.04 with Kodi nightly builds.

There are settings changes (more quality settings and a 'no title' setting) which may break existing installs.

### CODE REVIEW

**Comment by glk1001** [comment]
Checks all fail except for Ubuntu. Something about "versions.h"?

**Comment by glk1001** [comment]
Hi, 

There seems to be some problems with the compiler versions used in the checks. They don't support C++17. _**Ubuntu-ppa**_ and _**Windows 64-UWP**_ pass because they are using later compiler and SDK versions. Here's a summary of the failing checks:

**Windows 32 and 64**
``
Windows SDK too old: installed "10.0.14393.0" < minimum "10.0.17763.0"
``

**Jenkins**
``
CMake Error at CMakeLists.txt:33 (message):
  Could not find C++17 'optional' header.  Is libc++ up to date?
``

``
/home/jenkins/android-tools//android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: goom-libs-artifacts/lib/libgoom.a(logging.cpp.o): incompatible target
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/visualization.goom.dir/build.make:99: recipe for target 'libvisualization.goom.so' failed
``

``
/home/jenkins/android-tools//android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: goom-libs-artifacts/lib/libgoom.a(goom_control.cpp.o): Relocations in generic ELF (EM: 62)
goom-libs-artifacts/lib/libgoom.a: error adding symbols: File in wrong format
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
CMakeFiles/visualization.goom.dir/build.make:99: recipe for target 'libvisualization.goom.so' failed
``

``
Main.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[7]: *** [visualization.goom.20.0.1.dylib] Error 1
``

**Comment by glk1001** [comment]
Hi, 

I've tried again with a force push and updated code. There still seems to be problems with the compiler 
versions used in the build checks. They don't all support C++17. _**Ubuntu-ppa**_ and _**Windows 64-UWP**_ pass 
because they are using later compiler and SDK versions. Here's a summary of the failing checks:

**Windows 32 and 64**
<pre>
  Windows SDK too old: installed "10.0.14393.0" < minimum "10.0.17763.0"
</pre>

**Jenkins**
*build (android-aarch64)*
<pre>
  goom-libs-artifacts/lib/libgoom.a: error adding symbols: File in wrong format
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

*build (android-armv7)*
<pre>
  /home/jenkins/android-tools//android-ndk-r21e/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: goom-libs-artifacts/lib/libgoom.a(logging.cpp.o): incompatible target
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

*build (ios-aarch64)*
<pre>
  Could not find C++17 'optional' header.  Is libc++ up to date?
</pre>

*build (osx-x86_64)*
<pre>
  Could not find C++17 'optional' header.  Is libc++ up to date?
</pre>

*build (tvos-aarch64)*
<pre>
  "GOOM::GoomControl::GetLastShaderEffects() const", referenced from:
      CVisualizationGoom::UpdateGoomBuffer(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::vector<float, std::__1::allocator<float> > const&, CVisualizationGoom::PixelBufferData&) in Main.cpp.o
  ld: symbol(s) not found for architecture arm64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

*build (windows-i686)*
<pre>
  Long path problem:
    CMake Warning in src/goom/CMakeLists.txt:
      The object file directory
        F:/builds/workspace/binary-addons/kodi-windows-i686-Nexus/cmake/addons/build/visualization.goom-prefix/src/visualization.goom-build/goom_libs-prefix/src/goom_libs-build/src/goom/CMakeFiles/goom.dir/
      has 198 characters.  The maximum full path to an object file is 250
      characters (see CMAKE_OBJECT_PATH_MAX).  Object file
        src/visual_fx/filters/filter_zoom_vector_effects.cpp.obj
      cannot be safely placed under this directory.  The build may not work
      correctly.
</pre>

*build (windows-x86_64)*
<pre>
  Long path problem:
    CMake Warning in src/goom/CMakeLists.txt:
      The object file directory
        F:/builds/workspace/binary-addons/kodi-windows-x86_64-Nexus/cmake/addons/build/visualization.goom-prefix/src/visualization.goom-build/goom_libs-prefix/src/goom_libs-build/src/goom/CMakeFiles/goom.dir/
      has 200 characters.  The maximum full path to an object file is 250
      characters (see CMAKE_OBJECT_PATH_MAX).  Object file
        src/visual_fx/filters/filter_buffer_row_color_info.cpp.obj
      cannot be safely placed under this directory.  The build may not work
      correctly.
</pre>

**Comment by glk1001** [comment]
Hi Again. Force pushed the latest version. Restricted cmake to only accept more recent compilers. Hopefully this helps getting reliable C++-17 builds.

**Comment by lrusak** [comment]
Why not create a whole new addon?

**Comment by glk1001** [comment]
Probably a good idea. Given that 'kodi-community-addons' is not being
updated, I've been playing around with a Kodi Repository for Spotify and
Goom++ (https://github.com/glk1001/glk1001.github.io). To be honest, I'm
not sure how to go about getting these things officially added to Kodi.

**Comment by glk1001** [comment]
Most checks pass except Jenkins (required sigh!). Jenkins fails because of old compilers (android and ios), and Ubuntu with mysterious "java.lang.IndexOutOfBoundsException: index is out of range -1..0 (index = 1)" error. Can't debug that one.

**Comment by glk1001** [comment]
Will try to submit a separate Goom++ binary add-on.

**Pull request closed without merging**
