### PR TITLE
Goom++ - Initial commit.

### PR DESCRIPTION
**Pull request by glk1001**
Complete rewrite of Goom in C++14. 

Same algorithms (different tentacles) and lots more color from Gurki's 'vivid' library. Now use clangd and clang-format for code checking.

Have tested on Ubuntu 20.04 with Kodi 19 and LibreElec 9.2.2 with Kodi 18.

Have not built or tested with Windows.

### CODE REVIEW

**Comment by glk1001** [comment]
Hi, Could I please get some help with this request. Travis now passes (focal and Mac OS at least) but Jenkins and Windows are having problems with finding packages. What should I do about this? Thanks.

**Comment by AlwinEsch** [comment]
After a long of time ago on Kodi seen now your request, sorry that not earlier and that no other Team Member look about.

First thanks a lot to look for it and to makes it better!

Only on first test it has not worked and bring in Debug an `assert` fail with:
```gdb
kodi.bin: /home/alwin/Development/Kodi/_Addons/_alwin/visualization/visualization.goom/lib/goomutils/include/goomutils/colorutils.h:314: GOOM::Pixel GOOM::UTILS::GetBrighterColor(float, const GOOM::Pixel&, bool): Assertion `brightness >= 0.0 && brightness <= 2.0' failed.
Abgebrochen (Speicherabzug geschrieben)
```

**EDIT:** As release build it brings:
```
/home/alwin/Development/Kodi/kodi-N.build/kodi.bin: symbol lookup error: /home/alwin/.kodi/addons/visualization.goom/visualization.goom.so.3.4.0: undefined symbol: _ZN4GOOM3IFS9Colorizer20SetWeightedColorMapsESt10shared_ptrINS_5UTILS15RandomColorMapsEE
```

Also seems string id's not correct and on settings becomes showed as:
Bildschirmfoto von 2021-09-13 03-35-11

Will look further and also to check your another branch "goom_plus_plus_working"

**Comment by AlwinEsch** [comment]
About new added parts on `./lib` should be as most as possible done by the `depends` folder on addon.
- catch2: created a commit as example here https://github.com/AlwinEsch/visualization.goom/commit/8d57e9c173c8c265b9834681b9fb14d0a356de23
- fmt: Can understand why you added ./lib/fmt/include/format as come with C++20, only not sure if the best as `goom` library should also be possible to use then outside of addon
  - Maybe in the future, other programs outside of Kodi will be interested in it and "goom" could be an independent library again.
  - So maybe it would be also good to use `goomtests` and` goomutils` in one place (goom itself). 
- magic_enum: As there releases available (https://github.com/Neargye/magic_enum/archive/refs/tags/v0.7.3.tar.gz) can it be also used from there, about Ubuntu can for cases like this it added to our https://launchpad.net/~team-xbmc
- vivid: Also releases available like by magic_enum, https://github.com/sharkdp/vivid/archive/refs/tags/v0.7.0.tar.gz

Look also to have it C++17 compatible as this will be in Kodi soon.

With your version on branch "goom_plus_plus_working" was it possible to use and seen on screen and looks really good :+1: 

Nice with this debug show on it :grinning:, maybe good feature to enable/disable between Debug and Release builds or also on advanced addon settings?:
Bildschirmfoto von 2021-09-13 04-57-02

**Comment by AlwinEsch** [comment]
Look also then to allow disable of text show, as requested on https://github.com/xbmc/visualization.goom/issues/36, further is the text view a bit buggy if "Shows titles always" set on settings (jumps continues between formats).

Will create now a new release outside of the request, as a "Nexus" branch need to be created.

**Comment by glk1001** [comment]
Hi Alwin, Only just noticed your reply today (Oct 24th). I've fixed quite a few issues since you last looked. Also reorganized the directory structure a little to follow a recommended cmake structure. Could I create a new pull request with this new code. I will try and add in your suggestions.

**Comment by glk1001** [comment]
Will create a new pull request for Nexus.

**Pull request closed without merging**
